version: '3.8'

services:
  db:
    image: postgres:15
    container_name: roboblaze_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 125320
      POSTGRES_DB: roboblazedados
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - blaze_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: roboblaze_api
    restart: always
    depends_on:
      - db
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=125320
      - DB_NAME=roboblazedados
    networks:
      - blaze_network

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: roboblaze_worker
    restart: always
    depends_on:
      - db
      - api
    command: python blaze.py
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=125320
      - DB_NAME=roboblazedados
    networks:
      - blaze_network

volumes:
  postgres_data:

networks:
  blaze_network:
    driver: bridge
